<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Satyam" failures="1" tests="1" name="class1" time="3.588" errors="0" timestamp="2020-10-15T18:16:47 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="3.18">
    <failure type="java.lang.RuntimeException" message="Authentication Failed. Content of failed Response: io.restassured.internal.RestAssuredResponseImpl@75d366c2 , Status Code : 302">
      <![CDATA[java.lang.RuntimeException: Authentication Failed. Content of failed Response: io.restassured.internal.RestAssuredResponseImpl@75d366c2 , Status Code : 302
at apiEngine.endPoints.EndPoints.authenticateUser(EndPoints.java:29)
at stepDefination.defination.i_am_an_authorise_user(defination.java:35)
at âœ½.I am an authorise user(file:///C:/Users/satya.SATYAM/eclipse-workspace/RestAssured/src/test/resources/functions/test.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- class1 -->
