<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Satyam" failures="1" tests="1" name="class1" time="5.035" errors="0" timestamp="15 Oct 2020 17:06:08 GMT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.586">
    <failure type="java.lang.RuntimeException" message="Authentication Failed. Content of failed Response: io.restassured.internal.RestAssuredResponseImpl@2ec99035 , Status Code : 302">
      <![CDATA[java.lang.RuntimeException: Authentication Failed. Content of failed Response: io.restassured.internal.RestAssuredResponseImpl@2ec99035 , Status Code : 302
at apiEngine.endPoints.EndPoints.authenticateUser(EndPoints.java:28)
at stepDefination.defination.i_am_an_authorise_user(defination.java:33)
at âœ½.I am an authorise user(file:///C:/Users/satya.SATYAM/eclipse-workspace/RestAssured/src/test/resources/functions/test.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- class1 -->
